"""Guides par métier, partagés entre les zones desservies."""
from html import escape as e
DATA={
'plomberie':[
('Installer des sanitaires : préparer un devis complet','Le choix d’un lavabo, d’un WC ou d’une douche doit tenir compte de l’espace, de l’usage et des raccordements existants. Notez ce que vous souhaitez conserver et les changements recherchés : confort, rangement, entretien ou accessibilité. Un modèle choisi sur photo peut demander des adaptations qui modifient le budget.','Demandez une visite pour vérifier les arrivées, les évacuations et la place disponible. La proposition doit identifier les sanitaires, leur fourniture, la robinetterie, les raccordements et les finitions. Faites préciser si la dépose et l’évacuation des anciens équipements sont incluses.','Avant de commander, faites confirmer les références et les dimensions par le professionnel. À la réception, demandez une présentation du fonctionnement, les documents du matériel et la confirmation des contrôles réalisés.'),
('Fuite ou évacuation lente : préparer le diagnostic de plomberie','Une trace d’humidité, un écoulement sous un lavabo et une évacuation lente correspondent à des observations différentes. Notez la pièce, le moment d’apparition et la fréquence. Cette description aide à organiser la visite sans attribuer prématurément la panne à une canalisation ou à un appareil.','Le devis initial peut porter sur une recherche avant de chiffrer la remise en état. Demandez comment sera présentée la cause identifiée et comment une intervention supplémentaire sera proposée. Dans un immeuble, précisez si plusieurs logements sont concernés et si le syndic a été informé.','La réparation et les finitions ne sont pas toujours réalisées dans le même temps. Faites distinguer la remise en état du réseau, les reprises de support et les revêtements. Conservez le compte rendu et les références des éléments remplacés.'),
('Rénover la plomberie d’une cuisine : définir les limites du chantier','Le remplacement du mobilier peut modifier l’accès aux raccordements, même si l’évier reste à la même place. Préparez le plan du cuisiniste, la liste des appareils et les équipements à conserver. Faites vérifier la faisabilité des implantations avant de valider les meubles.','Le projet peut faire intervenir plombier, cuisiniste et autres professionnels. Demandez qui prépare les supports, qui raccorde les équipements et qui réalise les finitions. Le devis doit préciser les interfaces entre prestations pour éviter un poste oublié.','Si le logement reste occupé, convenez des périodes pendant lesquelles la cuisine sera indisponible. Faites confirmer l’ordre des livraisons et les conditions de réception. Une modification du plan après commande doit être évaluée avant exécution.')],
'electricite':[
('Installation électrique : préparer un plan des besoins','Un projet commence par les usages de chaque pièce : travail, cuisine, éclairage ou équipements ménagers. Préparez une liste des appareils et de leurs emplacements souhaités. Confiez au professionnel l’évaluation de l’installation et le choix des solutions techniques.','Demandez une proposition par pièce, distinguant équipements, fourniture, pose et finitions. L’état de l’existant et les adaptations éventuelles doivent être examinés avant commande. Le choix esthétique des prises et luminaires vient après la validation de la faisabilité.','À la réception, demandez les références des équipements, les consignes d’utilisation et les documents relatifs aux vérifications effectuées. Faites identifier les travaux réellement réalisés et les parties de l’installation qui n’étaient pas comprises dans la mission.'),
('Panne électrique : quelles informations transmettre au professionnel ?','Pour préparer une visite, décrivez uniquement ce que vous avez déjà observé : pièce concernée, moment du défaut et appareils affectés. Une panne ponctuelle et un défaut récurrent ne se décrivent pas de la même manière. Le diagnostic appartient à un électricien qualifié.','Ne démontez pas les prises, les appareils ou le tableau pour compléter la demande. Les références figurant sur vos factures ou documents sont utiles. Le professionnel pourra préciser les contrôles nécessaires et les conditions d’accès.','Faites distinguer le déplacement, la recherche du défaut et les travaux qui en découlent. Une proposition de réparation doit expliquer son périmètre et les vérifications prévues. Demandez comment sera soumis un éventuel complément avant sa réalisation.'),
('Rénovation électrique en logement occupé : organiser les travaux','Préparez la liste des pièces concernées et celles qui doivent rester accessibles. Informez le professionnel de l’occupation du logement et des contraintes horaires. L’organisation des interruptions et la protection des espaces doivent être étudiées avec lui.','Une rénovation peut impliquer plusieurs métiers. Faites préciser les saignées, les rebouchages, les revêtements et la peinture inclus dans chaque devis. Un budget limité aux équipements ne représente pas nécessairement le coût complet du chantier.','Demandez un phasage écrit, les critères de réception et la documentation remise. Comparez les offres sur un périmètre équivalent, avec les mêmes équipements et les mêmes finitions. Une durée définitive dépend de l’examen des lieux et des fournitures.')],
'climatisation':[
('Installation de climatiseur : comparer deux propositions','Deux devis peuvent viser une même pièce tout en proposant des appareils et des prestations différents. Comparez les références complètes, les caractéristiques documentées et les conditions de garantie. Faites expliquer le choix de la configuration à partir de l’usage réel de la pièce.','Les accessoires, les liaisons, les supports, la pose et la mise en service doivent être identifiés. Les conditions d’accès à l’unité extérieure et l’organisation dans le bâtiment sont à examiner avant validation. Le prix de l’appareil seul ne suffit pas à comparer.','Demandez quelles opérations d’entretien sont prévues par le fabricant et comment accéder au service après-vente. Vérifiez la documentation remise à la réception et faites préciser ce qui relève du matériel ou de la prestation de pose.'),
('Climatiseur bruyant : préparer une demande de réparation','Un bruit nouveau mérite une description précise : quand apparaît-il, dans quelle pièce est-il perceptible et depuis quand ? Indiquez la référence de l’appareil si elle figure sur vos documents. Un bruit décrit à distance ne permet pas d’identifier une pièce à remplacer.','Le professionnel doit déterminer si le défaut concerne l’appareil, sa pose ou un autre élément. Demandez le contenu de la visite de diagnostic et les modalités de chiffrage après examen. N’ouvrez pas l’équipement pour chercher la cause.','Avant de valider une réparation, faites préciser la disponibilité des pièces, les travaux retenus et les conditions de garantie. Un remplacement complet peut être étudié séparément si le diagnostic le justifie ; l’âge seul n’est pas un diagnostic.'),
('Rénover une climatisation : conserver ou remplacer les équipements ?','Le projet doit commencer par ce qui ne convient plus : confort, répartition entre pièces, fonctionnement ou entretien. Décrivez aussi les changements du logement depuis la pose initiale. Un équipement ancien peut correspondre à des besoins qui ont évolué.','Faites inventorier les appareils, supports et autres éléments que le professionnel envisage de conserver. Leur réutilisation doit être confirmée après examen. Demandez deux périmètres explicites lorsque réparation partielle et remplacement sont tous deux possibles.','Comparez le coût total, l’organisation de la dépose, les adaptations et la disponibilité future des pièces. Les performances annoncées doivent se rapporter à un modèle et à ses conditions d’usage. Aucun résultat chiffré ne doit être supposé pour votre logement sans évaluation.')],
'vitrerie':[
('Installer une paroi vitrée : définir le projet avant fabrication','Précisez l’usage de la paroi, son emplacement et l’aspect recherché. Une séparation intérieure, une fenêtre et une vitrine demandent des études différentes. Les dimensions indicatives servent à discuter du projet ; elles ne remplacent pas les mesures professionnelles.','Le devis doit préciser le vitrage, ses caractéristiques, ses finitions et les éléments de maintien. Faites examiner le support et les accès pour la manutention. Les contraintes du lieu guident le choix du produit.','Avant fabrication, validez la proposition écrite et les dimensions relevées par le professionnel. Faites préciser la pose, les protections et les finitions. La réception doit permettre de vérifier la correspondance avec les caractéristiques commandées.'),
('Remplacement de vitrage : comprendre le devis','Une proposition de remplacement doit identifier le vitrage existant et l’état du cadre. Une photo prise sans s’approcher d’un élément endommagé peut aider à préparer le rendez-vous, mais ne permet pas de commander un verre à elle seule.','Comparez composition, dimensions, finition, dépose et pose. Demandez si les accessoires et les adaptations du cadre sont inclus. Le professionnel doit confirmer la compatibilité avant fabrication.','L’accès, le transport et l’enlèvement de l’ancien vitrage font partie de l’organisation à préciser. Pour un commerce, convenez des horaires et de l’indisponibilité éventuelle de la zone. Ne manipulez pas vous-même un vitrage endommagé.'),
('Rénovation de fenêtres : vitrage seul ou ensemble complet ?','Définissez le problème que vous souhaitez résoudre : aspect, fonctionnement ou confort. Le vitrage et la menuiserie doivent être examinés ensemble. Un changement de verre ne corrige pas nécessairement un défaut du cadre ou de fermeture.','Demandez les conditions de conservation du support et les caractéristiques des solutions proposées. Un produit plus épais ou différent peut demander des adaptations. Le professionnel doit confirmer la faisabilité pour chaque ouverture.','Comparez le périmètre complet : dépose, fournitures, pose, finitions et enlèvement. La rénovation doit aussi prévoir l’occupation des pièces et l’accès aux ouvertures. Faites préciser les documents et conseils d’entretien remis.')],
'serrurerie':[
('Installer une serrure : choisir selon la porte et les usages','Précisez le type de porte, les utilisateurs et le fonctionnement attendu. Le choix du matériel dépend aussi du support et de l’équipement existant. Une serrure doit être compatible avec la porte ; une référence choisie uniquement sur son prix ne suffit pas.','Demandez le détail de la fourniture, du nombre de clés et des adaptations prévues. Pour un accès collectif, faites valider l’organisation par les personnes habilitées avant commande. Les caractéristiques annoncées doivent figurer sur la proposition.','Préparez les éléments justifiant votre autorisation à faire intervenir un professionnel sur cet accès. À la réception, demandez une démonstration du fonctionnement et les documents du matériel. Organisez la remise des clés aux personnes concernées.'),
('Porte difficile à fermer : préparer le rendez-vous de serrurerie','Décrivez quand la difficulté apparaît et si elle est récente. Le problème peut concerner la porte, son ajustement ou le mécanisme ; une description ne suffit pas à choisir la pièce à remplacer. Confiez l’examen à un professionnel.','Indiquez le type de porte et les interventions antérieures connues. Demandez le périmètre du diagnostic et comment la réparation sera chiffrée. Préparez votre autorisation d’accès au bien et les coordonnées de l’interlocuteur qui validera les travaux.','Comparez les solutions après diagnostic, en distinguant pièces, pose et adaptations. Le changement du cylindre et le remplacement d’un ensemble ne sont pas la même prestation. Conservez les références et les conditions de garantie.'),
('Rénover les fermetures : coordonner portes, serrures et clés','Un projet de rénovation peut concerner plusieurs portes avec des usages différents. Dressez l’inventaire des accès et des personnes qui les utilisent. Indiquez les équipements à conserver sans supposer leur compatibilité avec les nouveaux éléments.','Faites examiner ensemble support, porte et mécanisme. Demandez une proposition par accès et les adaptations nécessaires. Pour un local partagé, l’organisation des clés et la validation des travaux doivent être convenues avec les responsables.','Planifiez la continuité d’accès pendant le chantier et la remise des équipements à la réception. Demandez un récapitulatif des références posées. Toute modification du périmètre initial doit être expliquée et chiffrée avant validation.')],
'volets-roulants':[
('Installation de volets roulants : préparer les bonnes questions','Listez les ouvertures, leur usage et vos préférences de commande. Signalez les contraintes d’accès et l’aspect souhaité. Les dimensions définitives et le choix du système doivent être validés après examen professionnel.','Demandez le détail du tablier, du coffre, des accessoires et de la commande. Si une motorisation est envisagée, faites préciser les prestations associées et les autres métiers éventuellement nécessaires. La proposition doit couvrir l’ensemble du projet.','Avant commande, confirmez couleurs, références et finitions. Faites expliquer l’utilisation et les conditions d’entretien à la réception. Conservez les notices et les documents de garantie pour faciliter les demandes futures.'),
('Volet roulant bloqué : organiser le diagnostic','Notez la position du volet et le comportement observé sans chercher à le forcer. Indiquez s’il s’agit d’un modèle manuel ou motorisé et rassemblez les documents disponibles. Le diagnostic nécessite un examen du mécanisme par un professionnel.','La réparation peut concerner différentes pièces ; le remplacement du moteur ne doit pas être supposé à partir du seul blocage. Demandez ce que comprend la visite et comment sera proposée l’intervention après examen.','Faites préciser la disponibilité des pièces et les éléments conservés. Comparez une réparation et un remplacement sur leur coût complet, leurs délais confirmés et les conditions de garantie. L’accès au coffre peut également influer sur la prestation.'),
('Rénovation de volets : motoriser ou remplacer ?','Une motorisation vise un changement d’usage, alors qu’un remplacement peut aussi modifier le tablier et le coffre. Expliquez ce qui motive le projet et les ouvertures concernées. La décision dépend de l’état de l’ensemble existant.','Demandez au professionnel de confirmer ce qui peut être conservé et les adaptations nécessaires. La compatibilité de la commande, de la motorisation et des autres composants doit être examinée. Faites identifier les finitions dans la proposition.','Organisez les travaux ouverture par ouverture lorsque les pièces restent occupées. Validez les références avant commande, puis demandez une démonstration des commandes à la réception. Conservez la documentation de chaque équipement.')],
'aluminium':[
('Menuiserie aluminium : préparer une commande sur mesure','Définissez l’usage de chaque ouverture, le sens d’ouverture souhaité et l’aspect recherché. Les dimensions approximatives permettent une première discussion, mais la fabrication exige un relevé validé par le professionnel.','Comparez les références des profils, la finition, le vitrage éventuel et la quincaillerie. Demandez quelles caractéristiques sont documentées. La qualité du projet dépend aussi du support et des conditions de pose, pas seulement du matériau.','Validez les plans, teintes et accessoires avant fabrication. Faites préciser les délais annoncés, la dépose et les reprises incluses. À la réception, vérifiez avec le professionnel le fonctionnement et la conformité de la fourniture au devis.'),
('Coulissant aluminium difficile à utiliser : préparer la réparation','Décrivez le défaut de fonctionnement et les ouvertures concernées. Précisez s’il est récent ou progressif et si des travaux ont précédé son apparition. Le professionnel doit examiner l’ensemble avant d’identifier les composants en cause.','Rassemblez les références connues et les documents de pose. La disponibilité de pièces compatibles peut influencer la solution. Demandez une proposition distinguant diagnostic, pièces et intervention.','Faites préciser les limites de la réparation : mécanisme, ajustement, support ou autres éléments. Une remise en fonctionnement ne correspond pas forcément à une rénovation complète de l’ouverture. Conservez le détail des éléments remplacés.'),
('Rénover une menuiserie aluminium : comparer les périmètres','Commencez par vos priorités : fonctionnement, aspect ou confort. Demandez une évaluation du cadre, des ouvrants et des éléments associés. Remplacer la quincaillerie, modifier le vitrage et changer toute la menuiserie sont des projets différents.','Comparez les propositions sur des caractéristiques écrites et un même périmètre de finition. Faites préciser ce qui sera conservé et ce qui sera déposé. Les reprises de maçonnerie et de peinture peuvent relever de prestations séparées.','Conservez les accès nécessaires à l’occupation du logement dans le planning convenu. Avant fabrication, faites confirmer mesures et références. La réception doit couvrir les équipements et les finitions prévus dans la commande.')],
'chauffage':[
('Installation de chauffage : préparer l’étude du besoin','Présentez les pièces concernées, leurs usages et les équipements déjà présents. Le choix d’une solution doit être confié à un professionnel qui examine le bâtiment et les contraintes de compatibilité. Une puissance ou une technologie ne se choisit pas sur la seule surface.','Demandez une proposition détaillée séparant matériel, pose, adaptations et vérifications. Faites préciser les métiers impliqués et les travaux exclus. Les caractéristiques annoncées doivent correspondre aux références proposées.','Avant réception, convenez de la remise des notices, des conditions d’entretien et de la présentation de l’utilisation. Faites confirmer les documents relatifs à la mise en service. Conservez les références et les contacts utiles au suivi.'),
('Panne de chauffage : préparer la visite professionnelle','Rassemblez les documents du matériel et l’historique d’entretien disponible. Décrivez les observations déjà constatées et les pièces affectées. N’ouvrez pas l’équipement et ne tentez pas de manipulation technique pour compléter le diagnostic.','Demandez le contenu de la visite et les modalités de présentation de la cause identifiée. La réparation dépend de l’examen, des pièces disponibles et de l’état général. Un symptôme décrit à distance ne suffit pas à déterminer l’intervention.','Avant validation, faites préciser pièces, main-d’œuvre et contrôles professionnels. Si un remplacement est proposé, demandez son périmètre complet pour le comparer à la réparation. Les délais doivent être confirmés après diagnostic.'),
('Rénovation du chauffage : établir un inventaire avant décision','La rénovation peut concerner un appareil ou une installation plus large. Faites établir l’inventaire de ce qui sera conservé, remplacé ou adapté. Décrivez vos besoins actuels et les changements intervenus dans l’usage des pièces.','Demandez une comparaison des solutions avec références, travaux et entretien prévu. La compatibilité des éléments conservés doit être validée par un professionnel. Les économies futures ne peuvent pas être déduites du seul remplacement d’un appareil.','Le devis doit couvrir dépose, pose, adaptations, vérifications et finitions. Planifiez avec les intervenants les périodes d’indisponibilité. À la réception, demandez la documentation correspondant exactement au matériel installé.')],
'marbre':[
('Pose de marbre : choisir la finition et préparer le devis','Le choix porte sur la pierre, le format, le dessin de pose et la finition. Discutez de l’usage de la pièce et de l’entretien attendu avant commande. Un échantillon aide à préciser l’aspect, tout en tenant compte des variations naturelles de la pierre.','Faites examiner le support et les raccords avec les autres revêtements. Demandez le détail de la préparation, de la fourniture, de la pose, des bords et des seuils. Les découpes et finitions doivent être comprises dans la proposition.','Validez le calepinage avec le professionnel et convenez des conditions de réception. Faites préciser la protection du revêtement et le calendrier de remise en usage. Demandez les conseils d’entretien adaptés à la pierre et à sa finition.'),
('Marbre abîmé : préparer une évaluation de remise en état','Décrivez les défauts visibles : perte d’aspect, marques ou différences de niveau. Mentionnez les traitements connus et les zones les plus sollicitées. L’identification du matériau est nécessaire avant de proposer une remise en état.','Demandez quels défauts peuvent être atténués et quelles limites sont prévisibles. Un essai professionnel sur une zone convenue peut aider à définir le résultat attendu. Une méthode unique ne convient pas à toutes les pierres ni à toutes les marques.','Le devis doit distinguer préparation, traitement et finition. Faites préciser le travail des bords, la gestion du mobilier et les protections. Évaluez la proposition sur son contenu et sur les limites annoncées, pas seulement sur un tarif au mètre carré.'),
('Rénovation et cristallisation du marbre : définir le résultat attendu','La rénovation part de l’état du revêtement ; la cristallisation désigne une finition qui ne convient pas à tous les matériaux. Expliquez le résultat recherché et faites identifier la pierre. Une finition ne corrige pas automatiquement tous les défauts existants.','Demandez une proposition par étape, avec les surfaces, les bords et les seuils concernés. Faites préciser les limites du résultat et l’intérêt éventuel d’un essai préalable. Les traitements anciens connus doivent être signalés au professionnel.','Organisez l’accès aux pièces, le mobilier et les conditions de remise en usage. À la réception, demandez les recommandations d’entretien adaptées au traitement retenu. Conservez la description de la prestation pour les interventions futures.')]
}
KINDS=['installation','reparation','renovation']
ARTICLES=[]
for key, entries in DATA.items():
 for kind,(title,intro,scope,finish) in zip(KINDS,entries):
  ARTICLES.append((kind+'-'+key+'-guide',title,key,kind.upper(),[
   ('Comprendre le projet',intro),('Les points à faire préciser',scope),('Valider la prestation',finish),
   ('Organiser le rendez-vous dans votre secteur','À Casablanca, dans sa périphérie, à Mohammedia ou à El Jadida, indiquez votre commune ou quartier, une adresse complète et un point de repère. Précisez le type de bâtiment, l’étage, les modalités d’accès et les disponibilités de l’interlocuteur présent. Ces informations servent à préparer la visite ; les délais et les frais de déplacement doivent être confirmés. Retrouvez ci-dessous votre secteur et la page du service pour préparer les informations propres à votre demande.')]))

def guide_links(key):
 return '<section class="wrap prep"><h2>Guides : installation, réparation et rénovation</h2><div class="chips">'+''.join('<a href="/blog/'+a+'/">'+e(t)+'</a>' for a,t,k,tag,paras in ARTICLES if k==key)+'</div></section>'

def zone_directory(cities,slug):
 return '<section class="wrap prep"><h2>Les conseils pour votre zone</h2>'+''.join('<details><summary>'+e(c['name'])+'</summary><div class="chips">'+''.join('<a href="/blog/zones/'+c['slug']+'/'+slug(z)+'/">'+e(z)+'</a>' for z in c['zones'])+'</div></details>' for c in cities)+'</section>'

def service_locations(key,cities,slug):
 return '<section class="wrap prep"><h2>Retrouver ce service dans votre zone</h2>'+''.join('<details><summary>'+e(c['name'])+'</summary><div class="chips">'+''.join('<a href="/zones/'+c['slug']+'/'+slug(z)+'/'+key+'/">'+e(z)+'</a>' for z in c['zones'])+'</div></details>' for c in cities)+'</section>'

def publish_collections(page,heading,services,cities,slug):
 for c in cities:
  for z in c['zones']:
   p='/blog/zones/'+c['slug']+'/'+slug(z)+'/'
   body=heading('CONSEILS PAR ZONE','Préparer vos travaux — '+e(z)+' · '+e(c['name']),'Retrouvez les guides de chaque métier et les prestations proposées dans votre secteur.')
   for s in services:
    body+='<section class="wrap prep"><h2>'+e(s['name'])+' — '+e(z)+'</h2><p><a href="/zones/'+c['slug']+'/'+slug(z)+'/'+s['slug']+'/">Voir les prestations locales →</a></p><div class="chips">'+''.join('<a href="/blog/'+a+'/">'+e(t)+'</a>' for a,t,k,tag,paras in ARTICLES if k==s['slug'])+'</div></section>'
   page(p,'Conseils travaux — '+z+' · '+c['name'],'Guides des neuf métiers pour préparer vos projets dans le secteur '+z+' ('+c['name']+') : installation, réparation et rénovation.',body,[('Blog','/blog/'),(z,p)],index=False)
