from national import extend_cities, task_links, publish_tasks
from contact_content import contact_links, contact_bar, contact_body
from security_policy import CSP, HEADERS
from seo_metadata import metadata
from blog_guides import ARTICLES as GUIDE_ARTICLES, zone_directory, service_locations, publish_collections
from service_icons import service_icon
from seo_content import ARTICLES as EXTRA_ARTICLES, local_details, answered_questions, related
from local_pages import publish_all
from pathlib import Path
import json, html, unicodedata, re
ROOT=Path(__file__).parent; D=ROOT/'dist'; D.mkdir(exist_ok=True)
ORIGIN=json.loads((Path(__file__).parent/'site_config.json').read_text(encoding='utf-8'))['origin']
def slug(s):return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()).strip('-')
def e(s):return html.escape(str(s),quote=True)
CITIES=[
('Casablanca','Ain Diab, Maarif, Bourgogne, Racine, Gauthier, Oasis, Californie, Sidi Maarouf, Ain Sebaâ, Hay Mohammadi, Sidi Bernoussi, Roches Noires, Belvédère, Derb Sultan, Al Fida, Mers Sultan, Hay Hassani, Oulfa, Lissasfa, Sbata, Sidi Othmane, Moulay Rachid','De Ain Diab à Sidi Bernoussi, retrouvez les métiers de REPAREO dans les quartiers de Casablanca. Pour organiser une intervention, précisez le quartier, l’étage et les conditions d’accès au logement ou au local.'),
('Périphérie Casablanca','Dar Bouazza, Errahma, Bouskoura, Ville Verte, Nouaceur, Médiouna, Tit Mellil, Lahraouiyine','Dar Bouazza, Bouskoura, Nouaceur ou Médiouna : sélectionnez votre commune pour préparer votre projet. Une adresse précise et un point de repère permettent de confirmer le déplacement et son organisation.'),
('Mohammedia','Centre-ville, Parc, Al Alia, El Hassania, Rachidia, Wafa, Nasim, La Colline, Les Crêtes, Quartier des Plages, Mannesmann, Monica, Miramar, Sablettes, El Mansouria, Charrat, Beni Yakhlef, Chellalate, Zenata, Aïn Harrouda, Secteur industriel de Mohammedia','Notre secteur de Mohammedia regroupe les quartiers de la ville et les localités environnantes indiquées ci-dessous. Pour un commerce ou un site industriel, indiquez les horaires d’accès et les contraintes du site avant toute planification.'),
('El Jadida','Centre-ville, Cité Portugaise, Plateau, Essaada, Al Qods, Al Matar, Al Manar, Najd, Salam, Hay Essalam, Hay Al Amal, Hay Al Matar, Hay Al Farah, Hay Al Massira, Hay Al Moustakbal, Sidi Bouzid, Moulay Abdellah, Azemmour, Haouzia, Secteur industriel d’El Jadida','À El Jadida et dans le secteur de Sidi Bouzid, Azemmour ou Haouzia, préparez votre besoin d’installation ou de réparation. Précisez la localité exacte : les conditions de déplacement et la disponibilité sont à confirmer pour chaque demande.')]
CITIES=[dict(name=n,slug=slug(n),zones=z.split(', '),intro=t) for n,z,t in CITIES]
CITIES=extend_cities(CITIES,slug)
RAW=[
('plomberie','Plomberie','Plombier','Robinetterie, sanitaires et canalisations.','Une fuite, un équipement à remplacer ou une salle d’eau à aménager ? REPAREO prend en charge vos besoins de plomberie, du diagnostic à la pose.','Installation de plomberie','Pose de robinets, éviers, lavabos, WC et raccordements sanitaires. Le projet tient compte des arrivées d’eau, de l’évacuation et de l’accessibilité des équipements.','Réparation de plomberie','Recherche de l’origine d’une fuite, remplacement d’éléments défectueux et remise en état des équipements sanitaires après diagnostic.','Type d’équipement, emplacement de la fuite, ancienneté et photos prises à distance.','Un remplacement est-il toujours nécessaire ?','Pas systématiquement. Le diagnostic permet de distinguer une pièce remplaçable d’un équipement dont le remplacement complet est préférable.'),
('electricite','Électricité','Électricien','Éclairage, prises et installations électriques.','Un projet d’éclairage ou une installation qui présente un défaut ? Faites évaluer votre besoin par un professionnel avant toute modification électrique.','Installation électrique','Installation de points lumineux, prises et équipements adaptés au projet. L’état de l’existant et les besoins du logement sont examinés avant la proposition.','Réparation électrique','Diagnostic des défauts de fonctionnement et remplacement des éléments identifiés par le professionnel. Aucun diagnostic à distance ne remplace le contrôle sur place.','Équipements concernés, fréquence du défaut et références disponibles, sans ouvrir le tableau.','Pouvez-vous intervenir pour une rénovation ?','La rénovation peut être étudiée après examen de l’installation et définition des équipements à alimenter. Le périmètre des travaux est précisé avant intervention.'),
('climatisation','Climatisation','Climatisation','Installation, réparation et entretien de climatiseurs.','Un climatiseur adapté à votre pièce et une installation étudiée font la différence. REPAREO accompagne la pose, le diagnostic et la remise en état de votre climatisation.','Installation de climatiseur','Étude de l’emplacement, des besoins de la pièce et des contraintes de pose. La puissance et la configuration sont à valider avant le choix définitif de l’appareil.','Réparation de climatiseur','Évaluation des problèmes de refroidissement, d’écoulement ou de bruit. Le professionnel identifie la cause et les pièces nécessaires avant de proposer la réparation.','Marque, modèle, surface de la pièce, symptôme constaté et accessibilité des unités.','Quel climatiseur choisir pour ma pièce ?','Le choix dépend notamment du volume, de l’exposition et de l’isolation. Une évaluation permet de choisir un équipement adapté sans se limiter à la surface.'),
('vitrerie','Vitrerie','Vitrier','Vitrages, fenêtres et parois vitrées.','Remplacer un vitrage ou aménager une paroi demande des mesures précises. REPAREO étudie les dimensions, le support et l’usage pour proposer la solution appropriée.','Installation de vitrage','Pose de vitrages et de parois selon les dimensions relevées et les contraintes du support. Le type de verre est défini selon l’utilisation et l’emplacement.','Réparation et remplacement de vitrage','Évaluation du vitrage endommagé, prise de mesures et remplacement lorsque nécessaire. Le devis distingue le vitrage, les accessoires et la pose.','Dimensions approximatives, type de support et photo d’ensemble prise sans toucher le verre endommagé.','Les mesures à distance suffisent-elles ?','Des dimensions approximatives facilitent le premier échange. Les mesures définitives doivent être validées avant fabrication ou commande.'),
('serrurerie','Serrurerie','Serrurier','Serrures, cylindres et fermetures de portes.','Une serrure usée ou une fermeture difficile mérite un diagnostic précis. REPAREO étudie la compatibilité de la porte et des éléments à remplacer.','Installation de serrure','Pose de serrures, cylindres et accessoires compatibles avec votre porte. Le choix prend en compte l’usage, les dimensions et le niveau de protection recherché.','Réparation de serrure','Examen d’une fermeture défectueuse, d’un jeu anormal ou d’un mécanisme usé. Une réparation ou un remplacement est proposé selon l’état du matériel.','Type de porte, référence visible de la serrure et description du problème, sans forcer le mécanisme.','Faut-il remplacer toute la serrure ?','Selon le défaut, le remplacement peut concerner le cylindre, un accessoire ou le mécanisme complet. Le contrôle de compatibilité précède toute proposition.'),
('volets-roulants','Volets roulants','Volets roulants','Volets manuels, motorisés et mécanismes.','Un volet bloqué, bruyant ou un projet de motorisation ? REPAREO examine le tablier, les commandes et les contraintes de pose pour définir l’intervention.','Installation de volet roulant','Pose de volets roulants et étude de motorisation selon les ouvertures, le coffre disponible et les conditions d’alimentation.','Réparation de volet roulant','Diagnostic des blocages, défauts de commande ou éléments usés. Les pièces à remplacer sont déterminées après inspection de l’ensemble.','Dimensions de l’ouverture, commande manuelle ou motorisée et comportement du volet.','Peut-on motoriser un volet existant ?','Cela dépend de l’état du volet, de ses dimensions et du mécanisme. Une vérification permet de confirmer la faisabilité et le matériel compatible.'),
('aluminium','Aluminium','Menuiserie aluminium','Fenêtres, portes et baies en aluminium.','Pour une ouverture neuve ou une menuiserie à remettre en état, REPAREO étudie les dimensions, les profils et les accessoires nécessaires à votre projet.','Installation de menuiserie aluminium','Pose de fenêtres, portes et baies selon des mesures validées. Les choix de vitrage, de finition et de système d’ouverture sont définis avec le projet.','Réparation de menuiserie aluminium','Examen des problèmes de coulissement, fermeture ou étanchéité. Remplacement d’accessoires compatibles et réglage après diagnostic.','Dimensions approximatives, type d’ouverture, finition souhaitée et défaut éventuel.','Peut-on conserver le cadre existant ?','La possibilité de conserver le cadre dépend de son état, de sa fixation et de la compatibilité des nouveaux éléments. Elle doit être évaluée sur place.'),
('chauffage','Chauffage','Chauffage','Équipements de chauffage et radiateurs.','Une pièce insuffisamment chauffée ou un équipement à remplacer ? REPAREO étudie votre installation et votre usage avant de proposer une intervention.','Installation de chauffage','Étude et pose d’équipements de chauffage selon le type d’appareil, l’espace à chauffer et les contraintes du logement.','Réparation de chauffage','Diagnostic d’un défaut de fonctionnement et examen des composants concernés par un professionnel. La solution dépend de l’appareil et de la disponibilité des pièces.','Type d’énergie, marque, modèle et description du défaut, sans démonter l’appareil.','Le devis dépend-il du type de chauffage ?','Oui. La technologie, les raccordements, l’état de l’existant et l’accès à l’appareil influencent le périmètre de l’intervention.'),
('marbre','Marbre','Pose et cristallisation de marbre','Pose, rénovation et éclat des sols en marbre.','Un sol en marbre demande un traitement adapté à sa pierre et à son état. REPAREO accompagne la pose et la rénovation pour retrouver une finition homogène.','Installation et pose de marbre','Préparation du projet de pose selon le support, les dimensions, le calepinage et la finition souhaitée. L’état du support doit être vérifié avant les travaux.','Rénovation et cristallisation de marbre','Évaluation de l’usure, des taches et de la finition. Selon la pierre, une remise en état et une cristallisation peuvent être proposées ; tous les revêtements ne s’y prêtent pas.','Surface approximative, photos du sol, type de pierre si connu et résultat souhaité.','La cristallisation convient-elle à tous les sols ?','Non. La nature de la pierre et son état doivent être identifiés. Le professionnel confirme le traitement adapté avant toute application.')]
KEYS=['slug','name','trade','short','intro','install','install_text','repair','repair_text','prepare','q','a']
SERVICES=[dict(zip(KEYS,r)) for r in RAW]
PRESTATIONS=json.loads((ROOT/'prestations.json').read_text(encoding='utf-8'))
QUESTIONS=json.loads((ROOT/'questions.json').read_text(encoding='utf-8'))
(D/'assets').mkdir(exist_ok=True)
(ROOT/'content.json').write_text(json.dumps(dict(cities=CITIES,services=SERVICES),ensure_ascii=False,indent=2))
SERVICE_MENU='<details class="navzones navservices"><summary>Services <span aria-hidden="true">⌄</span></summary><div class="mega servicemenu"><a class="allservices" href="/services/">Tous nos services <span aria-hidden="true">→</span></a>'+''.join('<a class="service-menu-link" href="/services/'+s['slug']+'/">'+service_icon(s['slug'])+'<strong>'+s['name']+'</strong><span>'+s['short']+'</span></a>' for s in SERVICES)+'</div></details>'
NAV='<a href="/">Accueil</a>'+SERVICE_MENU+'<details class="navzones"><summary>Villes <span>⌄</span></summary><div class="mega">'+''.join('<details><summary>'+c['name']+'</summary><a href="/zones/'+c['slug']+'/">Tout le secteur</a>'+''.join('<a href="/zones/'+c['slug']+'/?secteur='+slug(z)+'">'+e(z)+'</a>' for z in c['zones'])+'</details>' for c in CITIES)+'</div></details><a href="/a-propos/">À propos</a><a href="/blog/">Blog</a>'
LOGO='<a class="brand" href="/" aria-label="REPAREO — accueil"><img src="/assets/logo.webp" width="174" height="48" alt="REPAREO"><span class="brandfallback">REPAREO<span>+</span></span></a>'
FOOT='<footer><div class="wrap footergrid"><div>'+LOGO+'<p>Installation & réparation.<br>Un interlocuteur pour votre habitat.</p></div><div><h3>Nos métiers</h3>'+''.join('<a href="/services/'+s['slug']+'/">'+s['name']+'</a>' for s in SERVICES)+'</div><div><h3>Nos secteurs</h3>'+''.join('<a href="/zones/'+c['slug']+'/">'+c['name']+'</a>' for c in CITIES)+'</div><div><h3>REPAREO</h3><a href="/a-propos/">À propos</a><a href="/blog/">Conseils & projets</a><a href="/contact/">Contact</a>'+contact_links()+'</div></div><div class="wrap footnote"><span>© 2026 REPAREO</span><span>Visuels de présentation générés pour la marque.</span></div></footer>'
PAGES=[]
def page(path,title,desc,body,crumbs=[],schema=None,index=True):
    title,desc=metadata(path,title,desc,SERVICES,CITIES)
    # Convert legacy zone selectors into real, linked neighborhood pages.
    text_links={}
    for city in CITIES:
        for zone in city['zones']:
            old='/zones/'+city['slug']+'/?secteur='+slug(zone)
            text_links[old]='/zones/'+city['slug']+'/'+slug(zone)+'/'
            for service in SERVICES:
                text_links['/zones/'+city['slug']+'/'+service['slug']+'/?secteur='+slug(zone)]='/zones/'+city['slug']+'/'+slug(zone)+'/'+service['slug']+'/'
    def rewrite_links(value):
        return re.sub(r'href="([^"]+)"',lambda m:'href="'+text_links.get(m.group(1),m.group(1))+'"',value)
    body=rewrite_links(body)
    url=ORIGIN+path
    bc=[('Accueil','/')]+crumbs
    breadcrumb='' if not crumbs else '<nav class="crumb wrap" aria-label="Fil d’Ariane">'+'<span>/</span>'.join('<a href="'+p+'">'+e(n)+'</a>' for n,p in bc)+'</nav>'
    graph=[{'@type':'Organization','@id':ORIGIN+'/#organisation','name':'REPAREO','email':'info@repareo.ma','telephone':'+212707072297','contactPoint':[{'@type':'ContactPoint','telephone':n,'contactType':'customer service','availableLanguage':'French'} for n in ['+212707072297','+212712123112']],'url':ORIGIN+'/', 'logo':ORIGIN+'/assets/logo.webp','areaServed':[{'@type':'Place','name':c['name']} for c in CITIES if c['zones']]}]
    if crumbs:graph.append({'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':i+1,'name':n,'item':ORIGIN+p} for i,(n,p) in enumerate(bc)]})
    graph.append({'@type':'WebSite','@id':ORIGIN+'/#website','url':ORIGIN+'/','name':'REPAREO','inLanguage':'fr-MA','publisher':{'@id':ORIGIN+'/#organisation'}})
    graph.append({'@type':'WebPage','@id':url+'#webpage','url':url,'name':title,'description':desc,'inLanguage':'fr-MA','isPartOf':{'@id':ORIGIN+'/#website'}})
    if schema:
        schema=dict(schema)
        schema['@id']=url+'#'+schema['@type'].lower()
        schema['url']=url
        if schema['@type']=='Article':
            schema['inLanguage']='fr-MA'
            schema['mainEntityOfPage']={'@id':url+'#webpage'}
            image_match=re.search(r'<img src="(/assets/[^"]+)"',body)
            if image_match:schema['image']=ORIGIN+image_match.group(1)
        graph.append(schema)
    home_css='<link rel="stylesheet" href="/home.css">' if path=='/' else ''
    text='<!doctype html><html lang="fr-MA"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="'+e(CSP)+'"><meta name="referrer" content="strict-origin-when-cross-origin"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+' | REPAREO</title><meta name="description" content="'+e(desc)+'"><meta name="robots" content="'+('index,follow' if index else 'noindex,follow')+'"><link rel="canonical" href="'+url+'"><meta name="theme-color" content="#102c3c"><meta property="og:title" content="'+e(title)+' | REPAREO"><meta property="og:description" content="'+e(desc)+'"><meta property="og:type" content="'+('article' if schema and schema.get('@type')=='Article' else 'website')+'"><meta property="og:url" content="'+url+'"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/style.css">'+home_css+'<link rel="stylesheet" href="/modern.css"><script defer src="/app.js"></script><script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('</','<\\/')+'</script></head><body><a class="skip" href="#main">Aller au contenu</a><div class="topbar"><div class="wrap"><span>INSTALLATION · RÉPARATION · RÉNOVATION</span><span>Votre projet, partout au Maroc</span></div></div><header><div class="wrap navwrap">'+LOGO+'<button class="menubtn" aria-expanded="false" aria-controls="nav">Menu ☰</button><nav id="nav" aria-label="Navigation principale">'+rewrite_links(NAV)+'<a class="button small" href="/contact/">Parlons de votre projet <span>↗</span></a></nav></div></header>'+breadcrumb+'<main id="main">'+body+'</main>'+FOOT+contact_bar()+'</body></html>'
    target=D/('index.html' if path=='/' else path.strip('/')+'/index.html'); target.parent.mkdir(parents=True,exist_ok=True);target.write_text(text,encoding='utf-8')
    if index:PAGES.append(path)
def pic(s,hero=False):
    return '<img src="/assets/'+s['slug']+'.webp" srcset="/assets/'+s['slug']+'-small.webp 480w, /assets/'+s['slug']+'.webp 1200w" sizes="(max-width:700px) 100vw, '+('50vw' if hero else '33vw')+'" width="1200" height="800" alt="Illustration d’un technicien REPAREO — '+s['name'].lower()+'" '+('fetchpriority="high"' if hero else 'loading="lazy"')+' decoding="async">'
def cards(city=None):
    return '<div class="servicegrid">'+''.join('<a class="servicecard" href="'+('/zones/'+city['slug']+'/'+s['slug']+'/' if city else '/services/'+s['slug']+'/')+'"><div class="cardphoto">'+pic(s)+'</div><div class="cardtext">'+service_icon(s['slug'])+'<h3>'+s['name']+'</h3><p>'+s['short']+'</p><span class="cardlink">Découvrir le service <b>↗</b></span></div></a>' for i,s in enumerate(SERVICES))+'</div>'
def heading(k,h,p):return '<section class="pageintro wrap"><div class="eyebrow">'+k+'</div><h1>'+h+'</h1><p class="lead">'+p+'</p></section>'
def citycards():return '<div class="citygrid">'+''.join('<a href="/zones/'+c['slug']+'/"><span class="cityindex">0'+str(i+1)+'</span><h3>'+c['name']+'</h3><p>'+str(len(c['zones']))+' quartiers et secteurs</p><span class="roundarrow">↗</span></a>' for i,c in enumerate(CITIES))+'</div>'
def questions(s,city=None):
    location=('en périphérie de Casablanca' if city['slug']=='peripherie-casablanca' else 'à '+city['name']) if city else 'dans votre secteur'
    attrs=(' data-question-area="'+e(city['name'])+'" data-question-location="'+e(location)+'"') if city else ''
    return '<section class="wrap service-questions"'+attrs+'><div class="eyebrow">VOS QUESTIONS</div><h2>Questions sur '+e(s['name'].lower())+' <span class="question-area-label">'+e(location)+'</span></h2><ol class="question-list">'+''.join('<li><span data-question-template="'+e(q)+'">'+e(q.replace('{lieu}',location))+'</span></li>' for q in QUESTIONS[s['slug']])+'</ol></section>'
def prestations(s):
    data=PRESTATIONS[s['slug']]
    return '<section class="wrap section prestations" aria-labelledby="prestations-title"><div class="sectionhead"><div><div class="eyebrow">EN DÉTAIL</div><h2 id="prestations-title">'+e(data['heading'])+'</h2></div></div><ul class="prestations-grid">'+''.join('<li><span class="prestation-number" aria-hidden="true">'+str(i+1).zfill(2)+'</span><h3>'+e(title)+'</h3><p>'+e(description)+'</p></li>' for i,(title,description) in enumerate(data['items']))+'</ul></section>'+task_links(s,SERVICES,PRESTATIONS,slug)
def cta():return '<section class="wrap cta"><div><div class="eyebrow">VOTRE PROCHAIN PROJET</div><h2>Un besoin dans votre maison ?<br>Commençons par le comprendre.</h2></div><a class="button light" href="/contact/">Préparer mon projet <span>↗</span></a></section>'
from home import render_home
body=render_home(SERVICES,CITIES,PRESTATIONS,pic,slug)
page('/','Installation et réparation au Maroc — 13 villes','REPAREO : plomberie, électricité, climatisation, vitrerie, serrurerie, volets roulants, aluminium, chauffage et marbre. Découvrez nos services et secteurs.',body)
page('/services/','Nos services d’installation et de réparation','Découvrez les neuf métiers REPAREO pour installer, réparer et rénover votre habitat à Casablanca et dans les secteurs voisins.',heading('9 MÉTIERS · UN MÊME INTERLOCUTEUR','Tous les savoir-faire<br>pour votre habitat.','Sélectionnez le métier qui correspond à votre installation ou à votre réparation.')+'<section class="wrap section compact">'+cards()+'</section>'+cta(),[('Services','/services/')])
for s in SERVICES:
    path='/services/'+s['slug']+'/'
    content=heading('INSTALLATION & RÉPARATION',s['trade']+' au Maroc',s['intro'])+'<section class="wrap detailsgrid"><div class="detailimage">'+pic(s,True)+'</div><div><article><h2>'+s['install']+'</h2><p>'+s['install_text']+'</p></article><article><h2>'+s['repair']+'</h2><p>'+s['repair_text']+'</p></article></div></section>'+prestations(s)+'<section class="wrap section"><div class="sectionhead"><h2>Votre service, près de chez vous.</h2></div><div class="citygrid">'+''.join('<a href="/zones/'+c['slug']+'/'+s['slug']+'/"><h3>'+c['name']+'</h3><p>'+s['name']+' · Installation & réparation</p><span>↗</span></a>' for c in CITIES)+'</div></section><section class="wrap prep"><h2>Préparer votre demande</h2><p>'+s['prepare']+'</p></section>'+related(s['slug'])+answered_questions(s,'Casablanca et sa région')+cta()
    page(path,s['trade']+' : installation et réparation',s['intro'],content,[('Services','/services/'),(s['name'],path)],{'@type':'Service','name':s['name'],'serviceType':s['name'],'provider':{'@id':ORIGIN+'/#organisation'},'areaServed':[c['name'] for c in CITIES]})
page('/zones/','Nos zones d’intervention','Explorez les neuf métiers REPAREO dans 13 villes du Maroc. Prestations et disponibilités à confirmer selon votre adresse.',heading('NOS ZONES','Votre ville.<br>Votre projet.','Choisissez votre ville et votre métier. Contactez-nous pour confirmer la disponibilité et organiser votre demande.')+'<section class="wrap section compact">'+citycards()+''.join('<section class="zonegroup"><h2><a href="/zones/'+c['slug']+'/">'+c['name']+'</a></h2><div class="chips">'+''.join('<a href="/zones/'+c['slug']+'/?secteur='+slug(z)+'">'+z+'</a>' for z in c['zones'])+'</div></section>' for c in CITIES)+'</section>',[('Zones','/zones/')])
for c in CITIES:
    path='/zones/'+c['slug']+'/'
    zoneopts='<option value="">Tout le secteur</option>'+''.join('<option value="'+slug(z)+'">'+z+'</option>' for z in c['zones'])
    selector='<div class="sectorpicker"><label for="sector">Votre quartier ou commune</label><select id="sector">'+zoneopts+'</select><p id="sector-note" aria-live="polite">Tous les quartiers de ce secteur sont présentés ci-dessous.</p></div>'
    page(path,'Installation et réparation — '+c['name'],c['intro'],heading('VOTRE SECTEUR',c['name'],c['intro'])+'<section class="wrap">'+selector+'</section><section class="wrap section"><h2>Les 9 métiers de REPAREO</h2>'+cards(c)+'</section><section class="wrap prep"><h2>Quartiers et localités desservis</h2><div class="chips">'+''.join('<a href="'+path+'?secteur='+slug(z)+'">'+z+'</a>' for z in c['zones'])+'</div><p>Le secteur sélectionné sera conservé lorsque vous ouvrez une page de service. La disponibilité et les modalités de déplacement restent à confirmer.</p></section>'+cta(),[('Zones','/zones/'),(c['name'],path)])
    for s in SERVICES:
        sp=path+s['slug']+'/'
        title=s['trade']+(' en périphérie de Casablanca' if c['slug']=='peripherie-casablanca' else ' à '+c['name'])
        content=heading(s['name'].upper()+' · '+c['name'].upper(),title,s['intro'])+'<section class="wrap">'+selector+'</section><section class="wrap detailsgrid"><div class="detailimage">'+pic(s,True)+'</div><div><article><h2>'+s['install']+' — '+c['name']+'</h2><p>'+s['install_text']+'</p></article><article><h2>'+s['repair']+' — '+c['name']+'</h2><p>'+s['repair_text']+'</p></article></div></section>'+prestations(s)+'<section class="wrap section localinfo"><div><div class="eyebrow">ORGANISER VOTRE INTERVENTION</div><h2>'+s['name']+' dans votre secteur</h2><p>'+c['intro']+'</p><h3>Les informations utiles pour votre projet</h3><p>'+s['prepare']+'</p><p>Le prix et le délai dépendent du diagnostic, du matériel et des conditions d’accès. Ils doivent être confirmés avant les travaux.</p><a class="button" href="/contact/?service='+s['slug']+'&ville='+c['slug']+'">Préparer ma demande ↗</a></div><aside><h3>Quartiers et localités</h3><div class="chips">'+''.join('<a href="'+sp+'?secteur='+slug(z)+'">'+z+'</a>' for z in c['zones'])+'</div></aside></section>'+local_details(s).replace('Casablanca',c['name'])+answered_questions(s,c['name'])+related(s['slug'])+'<section class="wrap section"><h2>Les autres services à '+c['name']+'</h2><div class="chips">'+''.join('<a href="'+path+t['slug']+'/">'+t['name']+'</a>' for t in SERVICES if t!=s)+'</div></section>'
        page(sp,title+' : installation et réparation',s['install']+' et '+s['repair'].lower()+' dans le secteur '+c['name']+'. Découvrez les prestations, les quartiers couverts et les informations utiles.',content,[('Zones','/zones/'),(c['name'],path),(s['name'],sp)],{'@type':'Service','name':title,'serviceType':s['name'],'provider':{'@id':ORIGIN+'/#organisation'},'areaServed':[{'@type':'Place','name':z+', '+c['name']} for z in c['zones']]})
page('/a-propos/','À propos de REPAREO','REPAREO réunit neuf métiers pour les projets d’installation, de réparation et de rénovation à Casablanca et dans sa région.',heading('REPAREO','Votre habitat mérite<br>une approche simple.','Rassembler les métiers dont votre logement ou votre local a besoin, et rendre chaque projet plus facile à préparer.')+'<section class="wrap detailsgrid"><div class="detailimage">'+pic(SERVICES[6],True)+'</div><div><h2>De l’installation à la remise en état.</h2><p>REPAREO est une entreprise spécialisée dans l’installation et la réparation. Plomberie, électricité, climatisation, vitrerie, serrurerie, volets roulants, aluminium, chauffage et marbre : notre offre couvre les équipements et les finitions de l’habitat.</p><p>Notre annuaire présente treize villes du Maroc ainsi que la périphérie de Casablanca. Les disponibilités et conditions de déplacement sont à confirmer auprès de REPAREO pour chaque adresse.</p><h3>Un projet bien défini avant de commencer</h3><p>La nature du besoin, les caractéristiques du matériel et les conditions d’accès permettent de définir le périmètre de chaque intervention.</p></div></section>'+cta(),[('À propos','/a-propos/')])
ARTICLES=[('preparer-projet-climatisation','Climatisation : préparer son projet d’installation','climatisation','PROJET · 4 MIN', [('Les caractéristiques de la pièce','Préparez la surface approximative, la hauteur sous plafond, le nombre d’ouvertures et l’exposition. Ces éléments aident le professionnel à étudier les besoins de la pièce.'),('Les emplacements à étudier','Photographiez la pièce et les emplacements envisagés depuis une position sûre. Le professionnel vérifiera l’accès, les contraintes de pose et les éventuelles autorisations nécessaires.'),('Comparer des devis complets','Demandez que la proposition précise le matériel, la pose, les accessoires, les conditions d’intervention et ce qui reste exclu. Deux prix ne sont comparables que si leur périmètre est similaire.'),('Préparer le rendez-vous','Indiquez votre ville, votre quartier et les contraintes d’accès. Si un appareil existe déjà, relevez uniquement les références visibles, sans le démonter.')]),('devis-installation-reparation','Installation ou réparation : que doit préciser un devis ?','plomberie','CONSEILS · 3 MIN',[('Un besoin décrit clairement','Une demande précise distingue le symptôme observé du résultat attendu. Signalez l’équipement concerné, son emplacement et les éventuelles interventions précédentes.'),('Le détail de la prestation','La proposition doit permettre de comprendre les travaux envisagés, les fournitures, la main-d’œuvre et les éventuels frais de déplacement. Demandez des précisions si un poste est ambigu.'),('Les limites du diagnostic initial','Certaines causes ne peuvent être identifiées qu’après examen sur place. Faites préciser comment les travaux supplémentaires éventuels seront expliqués et validés.'),('La planification','Le calendrier dépend notamment des pièces, de l’accès et de la disponibilité. Faites confirmer les conditions de réalisation avant de vous organiser.')]),('marbre-pose-ou-cristallisation','Marbre : distinguer pose, rénovation et cristallisation','marbre','MATÉRIAUX · 4 MIN',[('La pose concerne le projet de revêtement','Elle implique le choix de la pierre, les dimensions, le calepinage et la préparation du support. La finition attendue se discute dès le départ.'),('La rénovation part de l’état existant','Un sol terni, taché ou irrégulier nécessite une évaluation. L’objectif est d’identifier le matériau et la nature de l’usure avant de choisir un traitement.'),('La cristallisation n’est pas universelle','Ce traitement ne convient pas à tous les revêtements. Il doit être envisagé par un professionnel après identification de la pierre et vérification de son état.'),('Les éléments à préparer','Indiquez la surface approximative et fournissez des photos générales. Mentionnez les traitements précédents si vous les connaissez et la finition que vous recherchez.')])]
ARTICLES.extend(EXTRA_ARTICLES)
ARTICLES.extend(GUIDE_ARTICLES)
blogcards=''
for a,title,im,tag,paras in ARTICLES:
    p='/blog/'+a+'/'
    blogcards+='<a class="servicecard" href="'+p+'"><div class="cardphoto">'+pic(next(s for s in SERVICES if s['slug']==im))+'</div><div class="cardtext"><div class="eyebrow">'+tag+'</div><h2>'+title+'</h2><span class="cardlink">Lire le conseil ↗</span></div></a>'
    page(p,title,paras[0][1],heading(tag,title,'Des repères pour préparer votre échange avec un professionnel.')+'<section class="wrap detailsgrid"><div class="detailimage">'+pic(next(s for s in SERVICES if s['slug']==im))+'</div></section><article class="wrap article">'+''.join('<section><h2>'+h+'</h2><p>'+t+'</p></section>' for h,t in paras)+'<a class="button" href="/services/'+im+'/">Découvrir notre service ↗</a></article>'+related(im)+service_locations(im,CITIES,slug),[('Blog','/blog/'),(title,p)],{'@type':'Article','headline':title,'author':{'@id':ORIGIN+'/#organisation'},'publisher':{'@id':ORIGIN+'/#organisation'},'mainEntityOfPage':ORIGIN+p})
page('/blog/','Conseils pour vos projets d’installation et de réparation','Guides pour les neuf métiers REPAREO : installation, réparation et rénovation. Retrouvez les conseils et les prestations pour chacune de nos 71 zones.',heading('LE BLOG REPAREO','Un projet bien préparé<br>commence ici.','Des conseils pour poser les bonnes questions et mieux définir votre intervention.')+zone_directory(CITIES,slug)+'<section class="wrap section compact"><div class="servicegrid">'+blogcards+'</div></section>',[('Blog','/blog/')])
page('/contact/','Contact REPAREO : téléphone, WhatsApp et devis','Contactez REPAREO au 07 07 07 22 97 ou au 07 12 12 31 12. WhatsApp, info@repareo.ma et formulaire pour votre demande de devis.',heading('CONTACT REPAREO','Un projet ? Contactez-nous.','Décrivez votre besoin et votre secteur pour préparer votre intervention.')+contact_body(SERVICES),[('Contact','/contact/')])
page('/404/','Page introuvable','Retrouvez les services et les secteurs REPAREO.',heading('ERREUR 404','Cette page est introuvable.','Retrouvez votre chemin vers nos services ou notre page d’accueil.')+'<div class="wrap section"><a class="button" href="/">Retour à l’accueil</a></div>',index=False)
(D/'404.html').write_text((D/'404/index.html').read_text(encoding='utf-8'))
(D/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="7" fill="#102c3c"/><text x="5" y="24" font-family="Arial" font-weight="bold" font-size="25" fill="white">R</text><path d="M25 4v8m-4-4h8" stroke="#ed642c" stroke-width="3"/></svg>')
publish_all(page,heading,pic,SERVICES,CITIES,slug,ORIGIN,prestations)
publish_collections(page,heading,SERVICES,CITIES,slug)
publish_tasks(page,heading,pic,SERVICES,CITIES,PRESTATIONS,slug)
PAGES=list(dict.fromkeys(PAGES))
(D/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+ORIGIN+p+'</loc></url>' for p in PAGES)+'</urlset>')
(D/'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: '+ORIGIN+'/sitemap.xml\n')
(D/'_redirects').write_text('/accueil / 301\n/service /services/ 301\n/zone /zones/ 301\n/zones-intervention /zones/ 301\n/blogue /blog/ 301\n/a-propos-de-nous /a-propos/ 301\n')
(D/'_headers').write_text(HEADERS)

print('Generated',len(PAGES),'indexable pages;',sum(len(c['zones']) for c in CITIES),'listed sectors')
