"""National homepage: fast service selection, responsive editorial layout."""
from html import escape as e
from service_icons import service_icon

def render_home(services,cities,prestations,pic,slug):
    actual=[c for c in cities if c['slug']!='peripherie-casablanca']
    options=''.join('<option value="'+c['slug']+'">'+e(c['name'])+'</option>' for c in actual)
    svc=''.join('<option value="'+s['slug']+'">'+e(s['name'])+'</option>' for s in services)
    cards=''.join('<a class="n-service" href="/services/'+s['slug']+'/"><span class="n-service-top">'+service_icon(s['slug'])+'<span class="n-num">'+str(i+1).zfill(2)+'</span></span><h3>'+e(s['name'])+'</h3><p>'+e(s['short'])+'</p><span class="n-service-bottom">Explorer les prestations <span>↗</span></span></a>' for i,s in enumerate(services))
    citylinks=''.join('<a class="n-city" href="/zones/'+c['slug']+'/"><span>'+str(i+1).zfill(2)+'</span><strong>'+e(c['name'])+'</strong><span>↗</span></a>' for i,c in enumerate(actual))
    return '''<div class="national-home">
<section class="n-hero wrap"><div class="n-hero-copy"><div class="eyebrow">REPAREO · LES MÉTIERS DE L’HABITAT</div><h1>Vos travaux.<br>Un seul <em>réflexe.</em></h1><p>Installer, réparer, rénover. Trouvez le bon service pour votre logement ou votre local, puis préparons votre projet ensemble.</p><div class="actions"><a class="button" href="#trouver">Trouver mon service ↗</a><a class="n-quiet" href="/contact/">Parlons de votre projet</a></div><div class="n-hero-foot"><span><strong>09</strong> métiers complémentaires</span><span><strong>13</strong> villes à explorer</span></div></div><div class="n-hero-photo">'''+pic(services[6],True)+'''<div class="n-photo-label"><span>DE LA PREMIÈRE IDÉE<br>À LA FINITION.</span><strong>Le soin du détail.</strong></div><a class="n-photo-note" href="/services/aluminium/">Menuiserie aluminium <span>↗</span></a></div></section>
<section class="wrap n-finder" id="trouver" aria-labelledby="finder-title"><div><span class="eyebrow">COMMENÇONS SIMPLEMENT</span><h2 id="finder-title">De quoi avez-vous besoin ?</h2></div><form id="national-finder" action="/services/"><div><label for="n-city">Votre ville</label><select id="n-city" required><option value="">Choisir une ville</option>'''+options+'''</select></div><div><label for="n-service">Votre service</label><select id="n-service" required><option value="">Choisir un service</option>'''+svc+'''</select></div><button class="button" type="submit">Voir les prestations ↗</button></form><p>Le devis, le déplacement et la disponibilité sont confirmés après échange.</p><noscript><a href="/zones/">Consulter l’annuaire des villes</a></noscript></section>
<section class="wrap n-section" id="services"><div class="n-heading"><div><span class="eyebrow">NEUF MÉTIERS. UN MÊME SOIN.</span><h2>À chaque besoin,<br>son savoir-faire.</h2></div><p>Des équipements aux finitions, explorez les interventions adaptées à votre habitat.</p></div><div class="n-services">'''+cards+'''</div></section>
<section class="wrap n-feature"><div class="n-feature-photo">'''+pic(services[8])+'''</div><div class="n-feature-copy"><span class="eyebrow">INSTALLATION · RÉPARATION · RÉNOVATION</span><h2>Les petits détails.<br>La grande différence.</h2><p>Un sol à retrouver, une ouverture à remplacer, une pièce à rendre plus confortable. Chaque projet commence par votre besoin, les caractéristiques du lieu et le résultat souhaité.</p><a class="button" href="/contact/">Décrire mon projet ↗</a></div></section>
<section class="wrap n-section"><div class="n-heading"><div><span class="eyebrow">DU BESOIN AU PROJET</span><h2>Simple, à chaque étape.</h2></div></div><div class="n-steps"><article><span>01 /</span><h3>Vous nous expliquez.</h3><p>Votre service, votre ville et quelques détails sur le problème ou le projet.</p></article><article><span>02 /</span><h3>On précise ensemble.</h3><p>Le diagnostic, la disponibilité, les fournitures et le devis sont à confirmer.</p></article><article><span>03 /</span><h3>Le projet se concrétise.</h3><p>Un périmètre convenu et un rendez-vous organisé avant de commencer les travaux.</p></article></div></section>
<section class="n-city-band"><div class="wrap n-section"><div class="n-heading"><div><span class="eyebrow">VOTRE PROJET AU MAROC</span><h2>Et chez vous,<br>on commence par quoi ?</h2></div><p>Choisissez votre ville pour consulter les métiers. Contactez-nous pour confirmer la prise en charge à votre adresse.</p></div><div class="n-cities">'''+citylinks+'''</div><a class="n-periphery" href="/zones/peripherie-casablanca/">Dar Bouazza, Bouskoura et périphérie de Casablanca →</a></div></section>
<section class="wrap n-section n-faq"><div><span class="eyebrow">LES RÉPONSES UTILES</span><h2>Avant de<br>vous lancer.</h2><a class="textlink" href="/blog/">Lire nos conseils →</a></div><div><details><summary>Comment demander un devis ?</summary><p>Indiquez le service, votre ville, le quartier et ce que vous souhaitez réaliser. Des références visibles et des photos d’ensemble permettent de préparer l’échange. Le prix reste à confirmer selon l’évaluation.</p></details><details><summary>Les neuf services sont-ils disponibles partout ?</summary><p>La disponibilité dépend du métier, de votre adresse et du calendrier. Contactez REPAREO pour confirmer la prise en charge avant de prévoir une intervention.</p></details><details><summary>Peut-on demander plusieurs métiers ?</summary><p>Oui, décrivez l’ensemble du projet. Le périmètre et l’organisation de chaque prestation seront à préciser, notamment les fournitures et les finitions.</p></details><details><summary>Comment vous joindre rapidement ?</summary><p>Appelez le 07 07 07 22 97 ou le 07 12 12 31 12. Vous pouvez aussi préparer votre message WhatsApp depuis la page Contact.</p></details></div></section>
<section class="wrap n-final"><div><span class="eyebrow">ON PARLE DE VOTRE PROJET ?</span><h2>Votre habitat.<br>Notre point de départ.</h2></div><a class="button" href="/contact/">Préparer ma demande ↗</a></section></div>'''
