"""Contenus éditoriaux des premières pages locales prioritaires."""
from html import escape as e
from blog_guides import guide_links

# Chaque métier répond à un besoin concret, sans inventer de prix ni de chantiers.
LOCAL = {
 'plomberie': {
  'sections': [('Une fuite, un remplacement ou une rénovation ?', 'Une demande de plomberie commence par l’équipement concerné : évier, lavabo, WC, douche ou canalisation. Une fuite visible et une évacuation lente ne conduisent pas au même diagnostic. Décrivez ce que vous observez et les pièces touchées ; le professionnel déterminera si une réparation ponctuelle suffit ou si une reprise plus large doit être étudiée.'), ('Rénover une cuisine ou une salle de bains à Casablanca', 'Avant de déplacer un sanitaire, faites examiner le parcours des arrivées d’eau et des évacuations. Le devis doit distinguer la plomberie des reprises de carrelage, de peinture ou de mobilier. Dans un immeuble, indiquez si le problème concerne une partie privative ou semble lié à un réseau commun afin de préparer les échanges avec le syndic.'), ('Ce qui fait varier le devis de plomberie', 'L’accès à une canalisation, la référence du sanitaire et les fournitures nécessaires influencent le coût. Une réparation sur un raccord accessible n’a pas le même périmètre qu’une recherche nécessitant une ouverture et une remise en état. Demandez un détail du déplacement, du diagnostic, des pièces et des travaux de finition avant validation.')],
  'faq': [('Quel prix pour une recherche de fuite à Casablanca ?', 'Un montant fiable dépend de la localisation présumée, de l’accessibilité et des contrôles nécessaires. REPAREO ne publie pas encore de grille tarifaire. Demandez que le diagnostic et une éventuelle réparation soient distingués dans la proposition.'), ('Peut-on remplacer un WC sans refaire la salle de bains ?', 'Cela peut être possible si le nouveau modèle est compatible avec l’évacuation, l’arrivée d’eau et l’espace disponible. Les adaptations et finitions éventuelles doivent être vérifiées avant commande.')]
 },
 'electricite': {
  'sections': [('Définir le périmètre d’une installation électrique', 'Ajout d’éclairage, remplacement d’équipements ou rénovation d’un logement : indiquez l’usage de chaque pièce et les appareils prévus. Un professionnel doit examiner la capacité et l’état de l’installation existante avant de proposer de nouveaux points. Un nombre de prises seul ne suffit pas à définir un projet.'), ('Préparer une rénovation dans un logement occupé', 'À Casablanca, précisez votre quartier, l’étage, les horaires d’accès et les pièces qui doivent rester utilisables. Faites distinguer les travaux électriques des saignées, rebouchages et peintures. La proposition doit expliquer le phasage envisagé et les interruptions nécessaires, sans promettre une durée avant examen des lieux.'), ('Comprendre la proposition de réparation', 'Décrivez les défauts observés sans ouvrir le tableau ni démonter les équipements. Une proposition utile indique le diagnostic prévu, le matériel à remplacer et les vérifications réalisées par le professionnel. Le remplacement d’un appareil ne constitue pas à lui seul une évaluation de toute l’installation.')],
  'faq': [('Faut-il rénover toute l’installation pour ajouter des prises ?', 'Pas systématiquement. Le professionnel doit d’abord vérifier la compatibilité du projet avec l’existant et identifier les adaptations nécessaires.'), ('Que doit préciser un devis de rénovation électrique ?', 'Il doit décrire les pièces concernées, les équipements, les fournitures, la pose, les contrôles et les finitions incluses ou exclues. Les modalités d’accès et d’interruption sont également à convenir.')]
 },
 'climatisation': {
  'sections': [('Installation de climatiseur à Casablanca : choisir avant de poser', 'Le choix dépend de la surface, de la hauteur, de l’exposition et de l’usage de la pièce. Faites étudier l’emplacement des unités, le passage des liaisons et les contraintes du bâtiment avant d’acheter l’appareil. Un devis doit permettre de comprendre quelle configuration est proposée et pourquoi elle convient à votre projet.'), ('Réparation : décrire le symptôme sans présumer de la cause', 'Un appareil qui refroidit peu, un écoulement inhabituel ou un bruit peuvent avoir des origines différentes. Transmettez la marque, la référence visible, l’âge approximatif et les circonstances du défaut. Le diagnostic professionnel permet de définir la réparation ; une recharge ou un remplacement de pièce ne doit pas être proposé uniquement à partir d’un symptôme décrit à distance.'), ('Remplacer une ancienne climatisation', 'Pour comparer réparation et remplacement, examinez l’état général, la disponibilité des pièces, le coût des travaux et l’adéquation aux besoins actuels. Le réemploi des supports ou des liaisons doit être validé. En copropriété, les conditions de pose d’une unité extérieure sont à vérifier auprès des interlocuteurs concernés avant le chantier.')],
  'faq': [('Quelle puissance de climatiseur choisir pour mon appartement ?', 'La surface est un premier repère, mais le volume, l’exposition et l’isolation comptent également. Une évaluation du logement permet de confirmer la puissance et le type d’appareil.'), ('Un climatiseur qui refroidit mal manque-t-il forcément de fluide ?', 'Non. Ce symptôme ne permet pas de conclure à distance. Un professionnel doit rechercher l’origine du défaut avant de définir une intervention.')]
 },
 'vitrerie': {
  'sections': [('Un vitrage adapté à son usage', 'Une fenêtre, une vitrine et une paroi intérieure n’ont pas les mêmes contraintes. Décrivez l’emplacement, l’usage et le support existant. Le professionnel précisera le type de verre, les dimensions définitives et les accessoires nécessaires ; une dimension approximative sert à préparer le projet, pas à lancer la fabrication.'), ('Remplacement et rénovation de vitrages à Casablanca', 'Précisez si vous souhaitez remplacer seulement le vitrage ou reprendre également la menuiserie. Un changement de composition peut nécessiter de vérifier la compatibilité du cadre. Pour un commerce, indiquez les plages d’accès et l’organisation souhaitée autour de l’activité. Pour un logement, mentionnez l’étage et les conditions de manutention.'), ('Les postes à comparer sur le devis', 'Comparez la composition du vitrage, sa finition, la prise de mesures, la dépose, la pose et l’enlèvement de l’ancien élément. Faites préciser les éventuelles adaptations du support. Deux propositions de dimensions semblables peuvent porter sur des produits différents ; les caractéristiques écrites sont essentielles.')],
  'faq': [('Peut-on remplacer un vitrage sans changer la fenêtre ?', 'Cela dépend de l’état du cadre et de sa compatibilité avec le nouveau vitrage. Le professionnel doit examiner les éléments de maintien et les dimensions disponibles.'), ('Une photo suffit-elle pour commander un vitrage ?', 'Non. Elle aide à identifier le besoin, mais une validation des dimensions et des caractéristiques est nécessaire avant commande.')]
 },
 'serrurerie': {
  'sections': [('Installation de serrure : vérifier la porte et l’usage', 'Le choix d’une serrure dépend de la porte, du mécanisme existant et du besoin de protection. Une porte d’entrée de logement et une porte intérieure ne répondent pas au même usage. Faites confirmer la compatibilité du matériel et le contenu de la fourniture avant tout remplacement.'), ('Une fermeture difficile ne signifie pas toujours une serrure à changer', 'Le défaut peut concerner le mécanisme ou l’ajustement de la porte. Expliquez quand la difficulté apparaît et si elle est récente. L’examen professionnel évite de commander un équipement inadapté. Pour un accès partagé, indiquez également qui doit valider le choix et l’organisation des nouvelles clés.'), ('Préparer le rendez-vous à Casablanca', 'Précisez l’adresse, le type de porte et le contexte de votre demande. Pour une intervention touchant à l’accès d’un bien, préparez les éléments permettant de justifier votre autorisation. Le devis doit distinguer déplacement, diagnostic, fourniture, pose et adaptations éventuelles du support.')],
  'faq': [('Peut-on changer seulement le cylindre ?', 'Cela peut être envisagé si le mécanisme est en bon état et si le cylindre de remplacement est compatible. Le professionnel le confirme après examen.'), ('Une serrure plus coûteuse convient-elle à toutes les portes ?', 'Non. La compatibilité, la qualité du support et l’usage de la porte doivent être étudiés ensemble. Le prix seul ne permet pas de choisir.')]
 },
 'volets-roulants': {
  'sections': [('Installer un volet ou motoriser l’existant', 'Un projet neuf doit tenir compte des dimensions de l’ouverture, de la place du coffre et du mode de commande. Pour une motorisation, l’état du tablier et du mécanisme existant doit être évalué. Définissez aussi si les commandes seront individuelles ou regroupées afin de préparer une proposition cohérente.'), ('Réparation d’un volet roulant à Casablanca', 'Décrivez un blocage, un mouvement irrégulier ou un défaut de commande, ainsi que la position du volet. Le diagnostic porte sur l’ensemble du système avant le choix des pièces. Mentionnez l’étage et l’accès au coffre ; ces informations influencent l’organisation du rendez-vous et les conditions d’intervention.'), ('Une rénovation compatible avec les ouvertures', 'Un changement de fenêtre, de baie ou de finition de façade peut modifier le projet de volet. Faites coordonner les dimensions et les travaux de menuiserie. Le devis doit préciser le tablier, le coffre conservé ou remplacé, la motorisation éventuelle et les travaux complémentaires inclus.')],
  'faq': [('Un volet manuel peut-il devenir électrique ?', 'Souvent envisageable, ce projet reste soumis à la compatibilité du mécanisme, au poids du tablier, à l’espace disponible et aux conditions d’alimentation évaluées par les professionnels.'), ('Faut-il changer tout le volet lorsqu’il se bloque ?', 'Pas nécessairement. Le diagnostic doit identifier les éléments défectueux et vérifier si des pièces compatibles permettent une réparation durable.')]
 },
 'aluminium': {
  'sections': [('Fenêtres et baies : définir l’ouverture souhaitée', 'Pour une installation de menuiserie aluminium, précisez le type d’ouverture, les dimensions approximatives, le vitrage et la finition recherchée. Le relevé définitif doit intégrer le support et les contraintes de pose. Pensez également à l’usage quotidien : passage, entretien et place nécessaire à l’ouverture.'), ('Réparer un coulissement ou une fermeture', 'Un défaut de fonctionnement peut concerner des accessoires, le réglage ou l’état de la menuiserie. Le professionnel examine l’ensemble avant de confirmer les pièces compatibles. La description du défaut et des photos générales facilitent le premier échange sans remplacer cette vérification.'), ('Rénover les ouvertures à Casablanca', 'Pour un appartement, faites vérifier les contraintes de façade et l’organisation avec la copropriété. Pour une maison ou un local, précisez les zones qui doivent rester accessibles pendant les travaux. Demandez si le devis comprend la dépose, les reprises autour du cadre, l’étanchéité et l’évacuation des anciens éléments.')],
  'faq': [('Peut-on conserver le cadre lors d’une rénovation ?', 'Cela dépend de son état et de la compatibilité du nouveau projet. Le professionnel doit examiner les fixations, les dimensions et le support.'), ('Comment comparer deux devis de fenêtres aluminium ?', 'Comparez les dimensions, le système d’ouverture, les profils, le vitrage, les accessoires et le périmètre de pose. Faites préciser les finitions et reprises exclues.')]
 },
 'chauffage': {
  'sections': [('Choisir un équipement selon le logement', 'Décrivez les pièces à chauffer, leur usage, le confort attendu et le type d’installation existante. Une solution adaptée à une pièce ne convient pas automatiquement à tout le logement. Le professionnel doit confirmer les équipements compatibles et les contraintes avant la définition du projet.'), ('Organiser une réparation de chauffage à Casablanca', 'Transmettez le type d’énergie, la marque, le modèle et le défaut observé, sans démontage. Un rendez-vous de diagnostic permet de définir les composants concernés et de vérifier la disponibilité des pièces. Les interventions nécessaires et leurs modalités doivent être confirmées après cette évaluation.'), ('Rénovation : préciser ce qui sera conservé', 'Une rénovation peut concerner un appareil, plusieurs émetteurs ou une installation plus large. Demandez un inventaire des éléments conservés et remplacés, ainsi que les adaptations prévues. Le devis doit séparer le matériel, la pose, les contrôles professionnels et les éventuelles finitions ; aucun gain chiffré ne peut être promis sans étude.')],
  'faq': [('Peut-on remplacer un appareil par un modèle différent ?', 'Une vérification de compatibilité est nécessaire. La technologie, l’alimentation, les raccordements et les conditions de pose doivent être évalués.'), ('Comment choisir entre réparation et remplacement du chauffage ?', 'La décision prend en compte le diagnostic, l’état général, le coût des pièces, leur disponibilité et vos besoins. Demandez une comparaison du périmètre des deux solutions.')]
 },
 'marbre': {
  'sections': [('Pose de marbre : préparer le support et le dessin du sol', 'La pose commence par le choix de la pierre, du format et du calepinage. Faites examiner le support et les niveaux avant de commander le revêtement. Les raccords avec les pièces voisines, les seuils et la finition des bords doivent être définis dans le projet afin de comprendre le résultat attendu.'), ('Rénovation et cristallisation : deux notions à distinguer', 'Une rénovation part de l’état du sol : usure, différence de niveau, taches ou perte d’aspect. La cristallisation est une finition envisageable pour certaines pierres ; elle ne corrige pas tous les défauts. Le professionnel doit identifier le matériau et proposer une méthode adaptée, éventuellement après un essai sur une zone convenue.'), ('Préparer un chantier de marbre à Casablanca', 'Indiquez la surface, les pièces concernées, l’étage, l’occupation des lieux et le mobilier présent. Faites préciser les protections, le déplacement du mobilier, les bords et les seuils inclus. Le calendrier doit tenir compte des étapes de travail et des conditions de remise en usage définies pour le traitement retenu.')],
  'faq': [('La cristallisation enlève-t-elle toutes les taches ?', 'Non. Le résultat dépend de la pierre, de la nature de la marque et de sa profondeur. Une évaluation est nécessaire avant de promettre une finition.'), ('Le prix au mètre carré suffit-il à comparer les devis ?', 'Non. Comparez aussi la préparation, les traitements, le travail des bords, le mobilier, les protections et la finition prévue. Une même surface peut nécessiter des interventions différentes.')]
 }
}

ARTICLES = [
 ('choisir-climatiseur-appartement', 'Quel climatiseur choisir pour un appartement ?', 'climatisation', 'CHOIX DE MATÉRIEL', [
  ('Partir de la pièce et de son usage', 'Avant de comparer les appareils, décrivez l’espace à climatiser : pièce de vie, chambre ou bureau. Notez la surface approximative, la hauteur, l’exposition et les périodes d’occupation. Un appareil choisi uniquement sur la surface risque de ne pas correspondre aux besoins du logement. L’évaluation doit aussi tenir compte de l’isolation et des ouvertures.'),
  ('Faire vérifier les emplacements avant l’achat', 'L’emplacement des unités influence la faisabilité du projet et l’accès pour l’entretien. Dans un appartement, les règles de copropriété et les conditions de pose sur la façade sont à examiner. Présentez le projet au professionnel avant de commander ; il pourra confirmer la configuration et les adaptations nécessaires.'),
  ('Comparer le confort et le coût total', 'Regardez les caractéristiques documentées du modèle, les conditions de garantie et la disponibilité du service après-vente. Demandez un devis qui distingue l’appareil, les accessoires, les liaisons, la pose et les vérifications. Le prix affiché pour l’appareil seul ne décrit pas le coût du projet complet.'),
  ('Préparer les bonnes questions', 'Demandez pourquoi la puissance proposée convient à la pièce, quels éléments sont inclus et comment sera organisé l’accès aux unités. Faites préciser les conditions d’entretien et la documentation remise. Pour une installation à Dar Bouazza ou à Casablanca, l’adresse et les contraintes du bâtiment permettront de préparer le rendez-vous.')]),
 ('climatiseur-reparer-ou-remplacer', 'Climatiseur en panne : réparer ou remplacer ?', 'climatisation', 'RÉPARATION & REMPLACEMENT', [
  ('Commencer par un diagnostic', 'Une baisse de refroidissement ne suffit pas à identifier la cause. Décrivez le symptôme, les circonstances et l’historique des interventions. Le professionnel doit examiner l’appareil avant de proposer une réparation ou un remplacement. Une comparaison valable part d’un diagnostic, pas seulement de l’âge annoncé.'),
  ('Évaluer la réparation dans son ensemble', 'Demandez quelles pièces sont concernées, leur disponibilité et ce que comprend le prix annoncé. Une intervention ponctuelle peut être pertinente si le reste de l’appareil répond au besoin. À l’inverse, des défauts multiples peuvent justifier d’étudier une autre solution. Les conditions de garantie de l’intervention doivent être explicitées.'),
  ('Chiffrer aussi le remplacement complet', 'Le nouvel appareil n’est qu’un poste du projet : dépose, accessoires, adaptation de l’installation et pose doivent être précisés. Les supports ou liaisons existants ne sont pas automatiquement réutilisables. Le professionnel doit confirmer leur compatibilité avec la nouvelle configuration.'),
  ('Décider avec deux propositions comparables', 'Comparez le coût total, les délais liés aux pièces, les conditions de garantie et le confort attendu. Il n’existe pas de pourcentage universel imposant le remplacement. Une proposition écrite permet de choisir en comprenant ce qui est conservé, réparé ou remplacé, sans se fonder sur une économie future non démontrée.')]),
 ('renovation-salle-de-bains-preparer-plomberie', 'Rénovation de salle de bains : préparer les travaux de plomberie', 'plomberie', 'RÉNOVATION', [
  ('Lister ce qui change vraiment', 'Remplacer un robinet, changer des sanitaires et déplacer une douche sont des projets différents. Dressez une liste des équipements conservés et remplacés, puis indiquez vos priorités : usage, place disponible, entretien ou accessibilité. Cette description aide à établir un périmètre avant les choix décoratifs.'),
  ('Faire examiner les contraintes existantes', 'Le parcours des arrivées et évacuations, l’état des supports et l’accessibilité doivent être évalués par les professionnels. Un déplacement d’équipement peut entraîner des reprises supplémentaires. Dans un immeuble, signalez les éléments communs et les échanges nécessaires avec le syndic. Aucun plan à distance ne remplace l’examen des lieux.'),
  ('Coordonner les métiers et les finitions', 'La plomberie doit être coordonnée avec les autres travaux : supports, étanchéité, revêtements et équipements électriques lorsqu’ils sont concernés. Demandez qui prend en charge chaque partie et dans quel ordre. Les responsabilités et les limites de prestation doivent être comprises avant le chantier.'),
  ('Comparer les devis et organiser le logement', 'Vérifiez les références des sanitaires, la fourniture, la dépose, les raccordements, les finitions et l’évacuation des anciens éléments. Faites préciser les conditions de remise en service et l’organisation si la salle de bains est la seule du logement. À Casablanca, indiquez le quartier, l’étage et les modalités d’accès pour préparer cette planification.')])
]

def local_details(service):
    data=LOCAL[service['slug']]
    return '<section class="wrap article local-editorial">'+''.join('<section><h2>'+e(h)+'</h2><p>'+e(t)+'</p></section>' for h,t in data['sections'])+'</section>'

def answered_questions(service, location='Casablanca'):
    return '<section class="wrap prep"><h2>Vos questions sur '+e(service['name'].lower())+' — '+e(location)+'</h2>'+''.join('<details><summary>'+e(q.replace('Casablanca',location))+'</summary><p>'+e(a)+'</p></details>' for q,a in LOCAL[service['slug']]['faq'])+'</section>'

def related(service_slug, city_slug=None):
    entries=[('/blog/'+a+'/',title) for a,title,im,tag,paras in ARTICLES if im==service_slug]
    if service_slug=='climatisation': entries.insert(0,('/zones/peripherie-casablanca/dar-bouazza/climatisation/','Installation de climatiseur à Dar Bouazza'))
    if not entries:return guide_links(service_slug)
    return guide_links(service_slug)+'<section class="wrap prep"><h2>Pour préparer votre projet</h2><div class="chips">'+''.join('<a href="'+p+'">'+e(t)+'</a>' for p,t in entries)+'</div></section>'

